KIT ;
  IDL VERSION 1.2.8 ;
  TITLE 'Деятельность предприятия' ;
  AUTHOR '' ;
  CREATION DATE 27/3/2021 ;
  PROJECT NAME '' ;

  MODEL 'Деятельность предприятия'
    {LWI
    F 0 -13 0 0 0 400
      0 0 0 204 3 2 1 34
      100 'Arial'
    F 1 -24 0 0 0 400
      0 0 0 204 3 2 1 34
      190 'Arial'
    F 2 -11 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Courier New'
    F 3 -10 0 0 0 400
      0 0 0 204 3 2 1 34
      80 'Dialog'
    F 4 -12 0 0 0 400
      0 0 0 204 3 2 1 34
      90 'Dialog'
    D 0 0 0 0 0 1 0 0 2
    G 0 1
    T 'WORKING'
    R 77
    M 0 }
   ;
    AUTHOR '' ;
    PROJECT NAME '' ;
    DIAGRAM GRAPHIC A0 ;
      CREATION DATE 27/3/2021 ;
      REVISION DATE 27/3/2021 ;
      TITLE 'Деятельность предприятия' ;
      STATUS WORKING ;

      BOX 0 ;
        NAME '{LWI I 4 255 1 255}Деятельность предприятия' ;
        BOX COORDINATES (0,405;0,606) (0,581;0,424) ;
        DETAIL REFERENCE N A0 ;
      ENDBOX ;
      ARROWSEG 1 ;
        SOURCE BORDER ;
        PATH (0,019;0,47)(0,405;0,47) ;
