language: node_js
node_js: '10'

jobs:
  include:
    - stage: test
      addons:
        firefox: 'latest-esr'
      script:
        - TEST_BROWSERS=Firefox,ChromeHeadless xvfb-run npm run ci
    - stage: update examples
      script: './tasks/stages/update-examples'
    - stage: update demo
      script: './tasks/stages/update-demo'
    - stage: update website
      script: './tasks/stages/update-website'

stages:
  - test
  - name: update examples
    if: tag =~ ^v\d+\.\d+\.\d+$
  - name: update demo
    if: tag =~ ^v\d+\.\d+\.\d+$
  - name: update website
    if: tag =~ ^v\d+\.\d+\.\d+$