alias welcome="echo "Welcome $USER.""
alias path="echo -e ${PATH//:/\\n}"
alias .="cd .."
alias ..="cd ../.."
alias ...="cd ../../.."
alias ....="cd ../../../.."
alias cp="cp -iv"
alias mv="mv -iv"
alias rm="rm -iv"
alias x="exit"
alias sl="ls"
alias ll="ls -l"

alias Update="sudo apt-get update"
alias Upgrade="sudo apt-get upgrade"
alias Search="apt-cache search"
alias Autoremove="sudo apt-get autoremove"
alias Autoclean="sudo apt-get autoclean"
alias Purge="sudo apt-get remove –purge"
alias Install="sudo apt-get install"

alias clc="bash /home/vasya/bin/calc.sh"